# Generated by Django 6.0.4 on 2026-04-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenantuser',
            table='tenants_tenantuser',
        ),
    ]
