# Generated by Django 6.0.4 on 2026-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
