# Generated by Django 6.0.4 on 2026-04-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_tenant_status'),
        ('tenants', '0003_alter_tenantuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to='clients.tenant'),
            preserve_default=False,
        ),
    ]
