# Generated by Django 6.0.4 on 2026-04-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantuser_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='tenant',
        ),
    ]
